# Use postgres/example user/password credentials
version: '3.9'

services:

  db-test:
    image: postgres:15
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432" #локально:docker
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pomidoro-test


  cache-test:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6378:6379'



